version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQSL_USER}
      POSTGRES_PASSWORD: ${PSQSL_PASSWORD}
      POSTGRES_DB: ${PSQSL_DATABASE}
