version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumns:
      - ./images:/app/images
    # This is for testing purpose. 
    # TODO: Remove before deploying
    # ports:
    #   - 3000:3000
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
